version: "3.7"
volumes:
  shared-workspace:
    name: "data"
    driver: local
  hadoop_namenode:
  hadoop_datanode:
  
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    networks:
      spark-network:
          ipv4_address: 10.5.0.7
    ports:
      - 9870:9870
      - 9000:9000
      - 8020:8020
      - 50070:50070
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - shared-workspace:/workspace
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    env_file:
      - ./hadoop.env


  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    networks:
      spark-network:
          ipv4_address: 10.5.0.8
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env


  jupyterlab:
    image: jupyterlab
    restart: always
    container_name: jupyterlab
    networks:
      spark-network:
        ipv4_address: 10.5.0.5
    ports:
      - 3306:3306
    volumes:
      - shared-workspace:/opt/workspace
      - ./opt/jar/:/opt/jar/

  zeppelin:
    image: zeppelin
    restart: always
    container_name: zeppelin
    networks:
      spark-network:
        ipv4_address: 10.5.0.6
    ports:
      - 8890:8890
    volumes:
      - shared-workspace:/opt/workspace
      - ./opt/jar/:/opt/jar/      
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
  
  spark-master:
    image: spark-master
    restart: always
    container_name: spark-master
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
      - shared-workspace:/opt/workspace
      - ./opt/jar/:/opt/jar/
    environment:
      - SPARK_LOCAL_IP=spark-master

  spark-worker-1:
    image: spark-worker
    restart: always
    container_name: spark-worker-1
    hostname: spark-worker-1
    env_file: ./spark-worker.sh
    environment:
      - SPARK_LOCAL_IP=spark-worker-1
    ports:
      - 8081:8081
    networks:
      spark-network:
        ipv4_address: 10.5.0.3      
    volumes:
      - shared-workspace:/opt/workspace
      - ./opt/jar/:/opt/jar/      
    depends_on:
      - spark-master
      
  spark-worker-2:
    image: spark-worker
    restart: always
    container_name: spark-worker-2
    hostname: spark-worker-2
    ports:
      - 8082:8081
    env_file: ./spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks:
      spark-network:
        ipv4_address: 10.5.0.4      
    volumes:
      - shared-workspace:/opt/workspace
      - ./opt/jar/:/opt/jar/      
    depends_on:
      - spark-master
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/24

